INSERT INTO SHOP VALUES(1,'MASALA','RED CHILLI',10,9,'MDH');

SELECT* FROM SHOP;
INSERT INTO SHOP(ID,CATEGORY,NAME,DEPTID) VALUES(2,'TALC POWDER','NYCIL',12 );
INSERT INTO SHOP(ID,CATEGORY,NAME,DEPTID) VALUES(3,'FACE CREAM','FAIR AND LOVELY',14 );
INSERT INTO SHOP(ID,CATEGORY,NAME,DEPTID) VALUES(4,'HAIR OIL','PARACUITE',16 );

SELECT * FROM SHOP ORDER BY  NAME ASC;
SELECT * FROM SHOP WHERE DEPTID = 16;
UPDATE SHOP SET BATCHNO = 16 WHERE DEPTID =16;

ALTER TABLE  SHOP
ADD MRP INTEGER ;
UPDATE SHOP SET MRP = 160 WHERE DEPTID =16;
UPDATE SHOP SET MRP = 220 WHERE DEPTID =12;
UPDATE SHOP SET MRP = 130 WHERE DEPTID =10;
UPDATE SHOP SET MRP = 65 WHERE DEPTID =14;

SELECT MAX(MRP) FROM SHOP;
SELECT MIN(MRP) FROM SHOP;
SELECT SUM(MRP) FROM SHOP;
SELECT AVG(MRP) FROM SHOP;
SELECT COUNT(BATCHNO) FROM SHOP;