SELECT LEN('DATABASE');
SELECT UPPER('THIS IS A BOY');
SELECT LOWER('THIS IS A GIRL');
SELECT LTRIM('   ANYTHING'  );
SELECT RTRIM('  ANYTHING'    );
SELECT SUBSTRING('MICROSOFT',6,9);
SELECT REPLACE('MICROSOFT','MICRO', 'MAJOR');
SELECT REPLICATE('DUMMY ',5);